# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Build Wheel

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        python-version: ["3.9"]
        operating-system: [windows-latest]  # [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e '.[dev]'
      - name: Test with pytest
        run: |
          python3 -m pytest -m "not hardware" --cov=./ --cov-report=xml
      - name: Build wheel
        run: python setup.py bdist_wheel
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          if-no-files-found: error
